# Generated by Django 4.1.2 on 2023-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_available', models.CharField(default='Yes', max_length=122)),
                ('cur_floor', models.IntegerField()),
                ('status', models.CharField(default='STOP', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('dest_floor', models.IntegerField()),
                ('assigned_elevator_id', models.IntegerField(default=0)),
                ('is_pending', models.CharField(default='Yes', max_length=12)),
            ],
        ),
    ]
