# Generated by Django 4.1.2 on 2023-08-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='cur_floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='assigned_elevator_id',
            field=models.IntegerField(default=-1),
        ),
    ]
